import Link from "next/link";

export default function ManagerAcceptInvitePage() {
  return (
    <main className="mx-auto max-w-md px-6 py-12">
      <h1 className="text-3xl font-semibold">Manager Invite Flow Updated</h1>
      <p className="mt-3 text-neutral-600">
        This legacy page is deprecated. Manager onboarding now uses secure 48-hour claim links generated by admins.
      </p>

      <div className="mt-6 rounded-xl border border-neutral-200 bg-white p-5 shadow-sm">
        <p className="text-sm text-neutral-700">
          Ask your admin to generate a claim link from the Partner Portal. If you already have a manager account, sign in below.
        </p>

        <div className="mt-4 flex gap-3">
          <Link
            href="/manager-signin"
            className="rounded-md bg-neutral-900 px-4 py-2 text-sm font-semibold text-white hover:bg-neutral-700"
          >
            Manager Sign In
          </Link>
          <Link
            href="/events"
            className="rounded-md border border-neutral-300 px-4 py-2 text-sm font-medium text-neutral-700 hover:bg-neutral-100"
          >
            Back to Events
          </Link>
        </div>
      </div>
    </main>
  );
}
